[package]
name = "qrc"
version = "0.1.0"
authors = ["luokai <kaiv2@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcode = { version = "0.11", default-features = false }